#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # CoC
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    # wildignore = "target,out,build,.*"
    wildignore = "*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg,.bloop,.idea,*/out/*,.metals,*/node_modules/*"
    filemanager = "defx"

[[custom_plugins]]
  name = 'wakatime/vim-wakatime'
  merged = false

#[[custom_plugins]]
#  name = 'gerw/vim-HiLinkTrace'
#  merged = false

[[custom_plugins]]
  name = 'neoclide/coc-tabnine'
  build = 'yarn install --frozen-lockfile'
  merged = false

[[custom_plugins]]
  name = 'neoclide/coc-json'
  build = 'yarn install --frozen-lockfile'
  merged = false

[[custom_plugins]]
  name = 'neoclide/coc-html'
  build = 'yarn install --frozen-lockfile'
  merged = false

[[custom_plugins]]
  name = 'fannheyward/coc-xml'
  build = 'yarn install --frozen-lockfile'
  merged = false

[[custom_plugins]]
  name = 'vimwiki/vimwiki'
  merged = false

[[custom_plugins]]
  name = 'junegunn/goyo.vim'
  merged = false

[[custom_plugins]]
  name = 'junegunn/limelight.vim'
  merged = false

[[custom_plugins]]
  name = 'habamax/vim-asciidoctor'
  merged = false

[[custom_plugins]]
  name = 'diepm/vim-rest-console'
  merged = false

[[layers]]
  name = "core#statusline"
  enable = false

[[layers]]
  name = "core#tabline"
  enable = false

[[layers]]
  name = "ui"
  enable_sidebar = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools#dash"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"
  git-plugin = "gina"

[[layers]]
  name = "denite"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lsp"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#asciidoc"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#plantuml"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "test"
  [layers.override_config]
    scala_runner = "blooptest"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#scalametals"

[[layers]]
  name = "lang#toml"
